"""
Pydantic schemas for Smart Banking Assistant.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class SQLGenerationResponse(BaseModel):
    """
    Structured response generated by the LLM
    for Natural Language -> SQL conversion.
    """

    sql: str = Field(description="A read-only PostgreSQL SELECT query.")

    explanation: str = Field(
        description="Short explanation of what the SQL query does."
    )


class ChatRequest(BaseModel):
    query: str


class SourceDocument(BaseModel):
    document_name: str
    page_number: Optional[int] = None
    chunk_type: str
    score: float


class ChatResponse(BaseModel):
    query: str
    answer: str
    sources: List[SourceDocument]
